"""The AI half of the legacy server, ported for :8792 (edu-replatform Phase 04).

⛔ GENERATED BY EXTRACTION, NOT RETYPED. Every function and constant below was lifted from
   aws-quiz-app/edu_server.py by its AST node (``ast.get_source_segment``), so the prompts,
   the parsing tolerances, the book search weights and the vision trigger are the legacy's
   byte for byte. The ONLY edits are the adapter shims directly below this docstring:
     · ``load_module(root, name)`` resolves a book the legacy way (packaged first, then
       data/<name>.json) through content.py's guarded resolvers — ``root`` is ignored, it was
       the legacy's web directory and :8792 has its own;
     · BOOK_ROOT / LIBRARY_ROOT / MODULE_ID come from the one accessor (settings.store_path).
   If a behaviour here needs to change, change it in BOTH places or not at all — until Phase
   06 retires :8767, the two servers must answer the same question the same way.

⛔ Every function that calls a provider (provider_questions, fresh_questions, ask_tutor,
   grade_exercises) BLOCKS on urlopen for up to PROVIDER_TIMEOUT_SECONDS. They are called only
   from plain ``def`` route handlers, which FastAPI runs in its threadpool (plan C1).
"""

from __future__ import annotations

import base64
import json
import math
import os
import re
import secrets
from collections import defaultdict
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any
from urllib.error import HTTPError, URLError
from urllib.request import Request, urlopen

import content
from settings import ProviderConfig, store_path
from store import MODULE_ID

BOOK_ROOT = store_path("EDU_BOOK_ROOT")
LIBRARY_ROOT = store_path("EDU_LIBRARY_ROOT")
_MODULE_CACHE: dict[str, tuple[float, dict[str, Any]]] = {}


def load_module(root: Any, name: str | None = None) -> dict[str, Any]:
    """edu_server.py:load_module — packaged book first, then the legacy data/ shape. Cached by
    mtime so a re-import is picked up without a restart. Raises ValueError("Unknown book.")."""
    path = content.packaged_module_path(name)
    if path is None:
        try:
            path = content.resolve_data_module(name)
        except content.NotAFile as error:
            raise ValueError("Unknown book.") from error
    stamp = path.stat().st_mtime
    cached = _MODULE_CACHE.get(str(path))
    if cached and cached[0] == stamp:
        return cached[1]
    data = json.loads(path.read_text(encoding="utf-8"))
    _MODULE_CACHE[str(path)] = (stamp, data)
    return data


# ---------------------------------------------------------------- constants (extracted)
MAX_QUESTIONS = 10
MIN_FRESH_QUESTIONS = 5
MAX_FRESH_QUESTIONS = 30
QUESTIONS_PER_SECTION = 5
FRESH_PARALLEL_CALLS = 4
SPARE_SECTIONS = 2
PROVIDER_TIMEOUT_SECONDS = 120
BOOK_FILES = {"geron-homl3": "homl3.pages.json"}
ASK_MAX_QUESTION = 600
ASK_HISTORY_TURNS = 6
ASK_BOOK_PAGES = 3
ASK_EXCERPT_CHARS = 1_100
_BOOK_CACHE: dict[str, tuple[float, list[str]]] = {}
_BOOK_DF: dict[str, tuple[int, dict[str, int]]] = {}
_BOOK_CHAPTERS: dict[str, list[tuple[int, int, int]]] = {}
ASK_SAME_CHAPTER_BOOST = 2.5
ASK_NEAR_CHAPTER_BOOST = 1.4
ASK_COMMON_TERM_SHARE = 0.12
ASK_VISUAL_CHARS = 2_200
ASK_VISUAL_EXPLAIN_CHARS = 400
ASK_VISION_MAX_IMAGES = 2
ASK_VISION_MAX_BYTES = 1_200_000
ASK_VISION_COST = 3
ASK_FIGURE_REF = re.compile(r"\b(?:figure|fig\.?)\s*(\d{1,3})[-.](\d{1,3})\b", re.I)
ASK_VISUAL_DEICTIC = re.compile(
    r"\b(?:the|this|that|these|those|its|it's)\s+(?:"
    r"figure|chart|graph|diagram|plot|histogram|image|picture|screenshot|"
    r"axis|axes|legend|curve|scatter\s?plot|bar\s?chart|y-axis|x-axis)\b", re.I)
ASK_DESCRIPTION_MIN_CHARS = 40
EXERCISE_MAX_REQUEST_BYTES = 96 * 1024
EXERCISE_MAX_ANSWER = 1_500
EXERCISE_MAX_ITEMS = 40
EXERCISE_BOOK_PAGES = 6
ASK_STOPWORDS = frozenset("""a an the and or but if then than that this these those is are was were be been being
do does did of in on at to for from by with as it its he she they we you i what why how when which who whom can
could should would may might will just not no nor so such about into over under again further once here there all
any both each few more most other some only own same too very s t don now me my mine your yours
explain explains simply simple mean means meaning tell show shows understand difference between work works
working use used using need needs want get got make makes made thing things way ways lot really actually""".split())
ASSET_ID = re.compile(r"^(fig|eq)-\d{1,3}[-.]\d{1,3}$")
ASK_SYSTEM = (
    "You are the learner's tutor inside a study app. They are a junior data engineer: strong on SQL, "
    "tables, Spark and ETL, new to machine learning, and weak on Python, pandas and NumPy.\n\n"
    "HOW TO TALK. Like a person explaining to a colleague at a desk, not like a textbook. Short "
    "sentences. One idea at a time. Answer the actual question in the first sentence, then explain. "
    "Gloss every piece of jargon the first time you use it. Use an analogy from their world - a table, "
    "a SELECT, a GROUP BY, a full refresh versus an incremental load - whenever it is genuinely "
    "accurate, and skip it when it is not. Plain words over precise-sounding ones. No preamble, no "
    "'great question', no bullet-point dumps, no emoji. If they ask something short, answer short.\n\n"
    "WHERE ANSWERS COME FROM, in this order:\n"
    "1. THE LESSON they are reading. Use it first - it is on their screen.\n"
    "2. THE BOOK EXCERPTS supplied. Use these when the lesson does not cover it. It is fine to reach "
    "ahead of where they are; say so plainly when you do.\n"
    "3. YOUR OWN KNOWLEDGE, when neither covers it. Say that is what you are doing.\n\n"
    "FIRST LINE OF YOUR REPLY must be exactly one of:\n"
    "SOURCE: lesson\n"
    "SOURCE: book p.<page number>\n"
    "SOURCE: general\n"
    "Then a blank line, then the answer. Never invent a page number, a paper, an author or a URL. "
    "If you are unsure, say you are unsure - that is more useful to them than a confident guess."
)
SOURCE_LINE = re.compile(r"^\s*SOURCE:\s*(lesson|book|general)\b[^\n]*", re.I)
EXERCISE_SYSTEM = (
    "You are marking a junior data engineer's answers to the end-of-chapter exercises of a machine "
    "learning textbook. They are strong on SQL, tables, Spark and ETL, new to machine learning.\n\n"
    "MARK THE MEANING, NOT THE WORDING. They are writing what they understood in their own words. "
    "Different words for the right idea is CORRECT. Do not require the book's phrasing, its exact "
    "terms, or its examples. Do not require completeness beyond what the exercise actually asks: if "
    "it asks for four things, four is enough; if it asks 'what is X', a sound one-sentence answer is "
    "enough.\n\n"
    "VERDICTS, use exactly one per answer:\n"
    "correct   - the idea is right. Minor imprecision, a missing synonym, or clumsy phrasing is "
    "still correct.\n"
    "partial   - part of the answer is right and part is missing or muddled.\n"
    "incorrect - the idea is wrong, or the answer is empty, or it answers a different question.\n\n"
    "FEEDBACK. One or two short sentences, speaking to them directly. For 'correct', say what they "
    "got right and add at most one sharpening detail. For 'partial' and 'incorrect', say plainly "
    "what is missing or wrong and what the book says instead - never just 'wrong, try again'. Gloss "
    "any jargon you introduce. No preamble, no praise padding, no emoji.\n\n"
    "GROUND IT. Use the book excerpts supplied. If the excerpts do not settle a point, mark on your "
    "own knowledge of machine learning and say so in the feedback. Never invent a page number, a "
    "paper or an author.\n\n"
    "Reply with JSON ONLY, no prose around it, in exactly this shape:\n"
    '{"results": [{"n": 1, "verdict": "correct", "feedback": "..."}]}\n'
    "One entry per exercise you were given, with the same n. Nothing else in the object."
)
EXERCISE_VERDICTS = ("correct", "partial", "incorrect")


# ---------------------------------------------------------------- functions (extracted)
def strip_code_fence(text: str) -> str:
    value = text.strip()
    if value.startswith("```"):
        value = value.split("\n", 1)[1] if "\n" in value else ""
        if value.endswith("```"):
            value = value[:-3]
    return value.strip()


def all_theory_blocks(root: Path, name: str | None = None) -> list[tuple[int, int]]:
    """Every (chapter, block) pair, 1-based, that a fresh quiz may draw from."""
    sections = load_module(root, name)["tutorialData"]["sections"]
    return [(chapter, block) for chapter, section in enumerate(sections, 1) for block in range(1, len(section["items"]) + 1)]


def source_for_block(root: Path, chapter_number: int, block_number: int, name: str | None = None) -> tuple[str, str]:
    module = load_module(root, name)
    chapter = module["tutorialData"]["sections"][chapter_number - 1]
    item = chapter["items"][block_number - 1]
    if isinstance(item, str):
        # Older modules store a block as one plain string.
        return chapter["title"], item
    parts: list[str] = []
    for content in item.get("blocks", []):
        if content.get("content"):
            parts.append(content["content"])
        for entry in content.get("items", []):
            # Callout items are strings; "Go deeper" items are {term, text}.
            if isinstance(entry, str):
                parts.append(entry)
            elif isinstance(entry, dict) and entry.get("text"):
                parts.append(f"{entry.get('term', '')} — {entry['text']}")
        # Interactive code cells replaced a code card; keep their code in the
        # quiz source so the lesson does not lose it for AI question generation.
        for cell in content.get("cells", []) if content.get("type") == "code_cells" else []:
            if isinstance(cell, dict) and cell.get("source"):
                parts.append(f"```python\n{cell['source']}\n```")
    source = "\n\n".join(parts)
    if not source:
        raise ValueError("That theory block has no source text for AI generation.")
    return chapter["title"], f"{item.get('term', 'Theory block')}\n\n{source}"


def response_content(raw: bytes, content_type: str) -> str:
    """Return the assistant text from a Chat Completions response.

    Requests are sent with `stream: true`, so the normal case is a server-sent
    event stream whose delta chunks are joined here. A provider that ignores the
    flag and answers with one JSON body is accepted too.
    """
    text = raw.decode("utf-8", errors="replace")
    if "text/event-stream" in content_type or text.lstrip().startswith("data:"):
        parts: list[str] = []
        for line in text.splitlines():
            line = line.strip()
            if not line.startswith("data:") or line[5:].strip() == "[DONE]":
                continue
            try:
                chunk = json.loads(line[5:])
                parts.append(chunk["choices"][0].get("delta", {}).get("content") or "")
            except (json.JSONDecodeError, KeyError, IndexError, TypeError):
                continue
        return drop_think("".join(parts))
    return drop_think(json.loads(text)["choices"][0]["message"]["content"] or "")


# Measured 23-09-26: Claude via 9router's `cc/` provider opens plain-text replies
# with an empty reasoning tag ("<think></think>SOURCE: lesson ..."), which pushed
# the SOURCE line off the start and mislabelled every tutor answer "general".
# Strip a LEADING tag block only, never one mid-text.
_LEADING_THINK = re.compile(r"^\s*<think>.*?</think>\s*", re.DOTALL)


def drop_think(text: str) -> str:
    return _LEADING_THINK.sub("", text, count=1)


def parse_quiz_json(content: str) -> Any:
    value = strip_code_fence(content)
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        # Free models sometimes wrap the object in a sentence. Take the outermost
        # braces rather than failing a call that did produce the quiz.
        start, end = value.find("{"), value.rfind("}")
        if start < 0 or end <= start:
            raise
        return json.loads(value[start:end + 1])


def valid_question(question: Any) -> bool:
    if not isinstance(question, dict):
        return False
    options, explanations, correct = question.get("options"), question.get("explanations"), question.get("correct")
    return (
        isinstance(question.get("question"), str) and bool(question["question"].strip())
        and isinstance(options, list) and len(options) == 4 and all(isinstance(value, str) and value.strip() for value in options)
        and isinstance(explanations, list) and len(explanations) == 4 and all(isinstance(value, str) for value in explanations)
        and isinstance(correct, int) and not isinstance(correct, bool) and correct in range(4)
    )


def provider_questions(config: ProviderConfig, chapter_title: str, source: str, count: int, exact: bool = True) -> list[dict[str, Any]]:
    """Ask the model for `count` questions on one theory block.

    exact=True (the per-block quiz) rejects the whole answer on any defect.
    exact=False (a fresh quiz, many calls) keeps the valid questions and drops the
    rest, so one malformed item does not throw away a whole paid call.
    """
    instruction = (
        f"Create exactly {count} multiple-choice study questions using only the supplied theory. "
        "Do not invent facts or refer to material outside it. Return a JSON object with a questions array. "
        "Every question needs question (string), options (exactly four strings), correct (zero-based index), "
        "and explanations (exactly four short strings; explain why each option is right or wrong)."
    )
    body: dict[str, Any] = {
        "model": config.model,
        "messages": [{"role": "system", "content": instruction}, {"role": "user", "content": f"Chapter: {chapter_title}\n\nTheory block:\n{source}"}],
        "temperature": 0.3,
        # Streamed on purpose. Measured 15-09-26 through 9router's `edu-arg` combo:
        # a non-streamed request returned HTTP 200 with `"content": ""` (the router
        # translates to the provider's responses API and loses the text), while the
        # same request streamed returned the full quiz. response_content() joins
        # the chunks, and still accepts a plain JSON body from providers that
        # ignore the flag.
        "stream": True,
    }
    if config.json_mode:
        body["response_format"] = {"type": "json_object"}
    request = Request(config.api_url, data=json.dumps(body).encode("utf-8"), headers={"Authorization": f"Bearer {config.api_key}", "Content-Type": "application/json"}, method="POST")
    try:
        with urlopen(request, timeout=PROVIDER_TIMEOUT_SECONDS) as response:
            content = response_content(response.read(), response.headers.get("Content-Type", ""))
    except HTTPError as error:
        raise ValueError(f"Provider request failed ({error.code}).") from error
    except (URLError, TimeoutError, OSError) as error:
        raise ValueError("Provider could not be reached.") from error
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as error:
        raise ValueError("Provider returned an invalid quiz response.") from error
    try:
        parsed = parse_quiz_json(content)
    except json.JSONDecodeError as error:
        raise ValueError("Provider returned an invalid quiz response.") from error
    questions = parsed.get("questions") if isinstance(parsed, dict) else None
    if not isinstance(questions, list):
        raise ValueError("Provider returned an invalid quiz response.")
    if exact:
        if len(questions) != count:
            raise ValueError("Provider did not return the requested number of questions.")
        if not all(valid_question(question) for question in questions):
            raise ValueError("Provider returned a question with an invalid schema.")
    kept = [question for question in questions if valid_question(question)][:count]
    if not kept:
        raise ValueError("Provider returned no usable questions.")
    return [shuffled_question(q) for q in kept]


def shuffled_question(question: dict[str, Any]) -> dict[str, Any]:
    """Shuffle the four options, carrying each explanation and the answer with them.

    Models put the right answer first far more often than chance: a live 20-question
    run on 15-09-26 had it at option A 13 times. Unshuffled, a learner can score well
    by always picking A.
    """
    order = list(range(4))
    secrets.SystemRandom().shuffle(order)
    return {
        "question": question["question"].strip(),
        "options": [question["options"][index].strip() for index in order],
        "correct": order.index(question["correct"]),
        "explanations": [question["explanations"][index].strip() for index in order],
    }


def fresh_questions(config: ProviderConfig, root: Path, count: int,
                    blocks: set[tuple[int, int]] | None = None, name: str | None = None) -> tuple[list[dict[str, Any]], list[str]]:
    """Write a new quiz with the model from randomly chosen book sections.

    Sections are drawn without replacement; a couple of spares are held back so a
    section whose call fails is replaced instead of shrinking the quiz. Returns the
    questions (shuffled) and the error messages of any calls that failed.
    """
    pool = all_theory_blocks(root, name)
    if blocks:
        # The learner ticked chapters and blocks on the quiz setup screen (17-09-26).
        pool = [target for target in pool if target in blocks]
    rng = secrets.SystemRandom()
    needed = -(-count // QUESTIONS_PER_SECTION)
    picks = rng.sample(pool, min(len(pool), needed + SPARE_SECTIONS))
    plan = [(picks[index], min(QUESTIONS_PER_SECTION, count - index * QUESTIONS_PER_SECTION)) for index in range(min(needed, len(picks)))]
    spares = picks[len(plan):]

    def one(target: tuple[int, int], size: int) -> list[dict[str, Any]]:
        chapter_title, source = source_for_block(root, *target, name)
        return provider_questions(config, chapter_title, source, size, exact=False)

    questions: list[dict[str, Any]] = []
    errors: list[str] = []
    with ThreadPoolExecutor(max_workers=FRESH_PARALLEL_CALLS) as pool_executor:
        pending = [(size, pool_executor.submit(one, target, size)) for target, size in plan]
        while pending:
            retry: list[tuple[int, Any]] = []
            for size, future in pending:
                try:
                    questions.extend(future.result())
                except (ValueError, IndexError, KeyError, OSError, json.JSONDecodeError) as error:
                    errors.append(str(error))
                    if spares:
                        retry.append((size, pool_executor.submit(one, spares.pop(), size)))
            pending = retry
    rng.shuffle(questions)
    return questions[:count], errors


def book_pages(module_id: str) -> list[str]:
    """The book's page text, cached by mtime. Empty list when a module has no book."""
    name = BOOK_FILES.get(module_id)
    if not name:
        return []
    path = BOOK_ROOT / name
    try:
        stamp = path.stat().st_mtime
    except OSError:
        return []
    cached = _BOOK_CACHE.get(module_id)
    if cached and cached[0] == stamp:
        return cached[1]
    try:
        pages = json.loads(path.read_text(encoding="utf-8")).get("pages") or []
    except (OSError, json.JSONDecodeError, AttributeError):
        return []
    pages = [str(p or "") for p in pages]
    _BOOK_CACHE[module_id] = (stamp, pages)
    return pages


def book_document_frequency(module_id: str) -> dict[str, int]:
    """How many pages each word appears on, cached per book."""
    cached = _BOOK_DF.get(module_id)
    pages = book_pages(module_id)
    if cached and cached[0] == len(pages):
        return cached[1]
    df: dict[str, int] = defaultdict(int)
    for text in pages:
        for word in set(re.findall(r"[a-z0-9]+", text.lower())):
            df[word] += 1
    _BOOK_DF[module_id] = (len(pages), df)
    return df


def book_chapters(module_id: str) -> list[tuple[int, int, int]]:
    """(chapter number, first page, last page) from the book's own outline.

    Used to keep the search inside the body -- the index and the table of contents
    are dense with rare words and otherwise win every query -- and to prefer the
    chapter the learner is actually reading.
    """
    cached = _BOOK_CHAPTERS.get(module_id)
    if cached is not None:
        return cached
    name = BOOK_FILES.get(module_id)
    rows: list[tuple[int, int, int]] = []
    if name:
        try:
            outline = json.loads((BOOK_ROOT / name).read_text(encoding="utf-8")).get("outline") or []
        except (OSError, json.JSONDecodeError, AttributeError):
            outline = []
        starts: list[tuple[int, int]] = []
        tail = len(book_pages(module_id))
        for entry in outline:
            if not isinstance(entry, dict):
                continue
            found = re.match(r"^\s*(\d{1,2})\.\s", str(entry.get("title") or ""))
            page = entry.get("page")
            if found and isinstance(page, int):
                starts.append((int(found.group(1)), page))
            elif isinstance(page, int) and starts and re.match(r"^\s*(Appendix|Index)\b", str(entry.get("title") or ""), re.I):
                tail = min(tail, page)
        starts.sort()
        for i, (number, start) in enumerate(starts):
            end = starts[i + 1][1] - 1 if i + 1 < len(starts) else tail - 1
            rows.append((number, start, end))
    _BOOK_CHAPTERS[module_id] = rows
    return rows


def book_search(module_id: str, query: str, limit: int = ASK_BOOK_PAGES, chapter: int | None = None) -> list[dict[str, Any]]:
    """Keyword search over the book, weighted by how rare each word is.

    Deliberately not embeddings: the book is ~1.8 MB, the lesson already pins the
    topic, and a vector store would add a dependency and a build step for recall
    this does not need.

    Plain term-frequency was measured returning pages 877/554/256 for "why is the
    error squared" -- the filler words carried the match. Weighting each term by
    1/document-frequency makes a word that appears on 40 pages outrank one that
    appears on 600, which is what puts the right chapter first.
    """
    pages = book_pages(module_id)
    terms = {w for w in re.findall(r"[a-z0-9]+", query.lower()) if len(w) > 2 and w not in ASK_STOPWORDS}
    if not pages or not terms:
        return []
    chapters = book_chapters(module_id)
    body = (chapters[0][1], chapters[-1][2]) if chapters else (0, len(pages) - 1)
    here = next(((a, b) for n, a, b in chapters if n == chapter), None)
    df = book_document_frequency(module_id)
    total = len(pages)
    weights = {t: math.log(1 + total / (1 + df.get(t, 0))) for t in terms}
    # A term on more than this share of pages says nothing about which page to pick.
    common = {t for t in terms if df.get(t, 0) > total * ASK_COMMON_TERM_SHARE}
    useful = {t for t in terms if t not in common} or terms
    scored: list[tuple[float, int, int]] = []
    for index, text in enumerate(pages):
        if not body[0] <= index <= body[1]:
            continue                       # front matter, appendices and the index
        low = text.lower()
        score = sum(low.count(term) * weights[term] for term in useful if term in low)
        if not score:
            continue
        if here and here[0] <= index <= here[1]:
            score *= ASK_SAME_CHAPTER_BOOST          # what they are reading now
        elif here and here[0] - 40 <= index <= here[1] + 40:
            score *= ASK_NEAR_CHAPTER_BOOST
        scored.append((round(score, 4), len({t for t in useful if t in low}), index))
    scored.sort(reverse=True)
    out: list[dict[str, Any]] = []
    for _score, _distinct, index in scored[:limit]:
        text = pages[index]
        low = text.lower()
        first = min((low.find(t) for t in useful if t in low), default=0)
        start = max(0, first - ASK_EXCERPT_CHARS // 3)
        out.append({"page": index, "text": " ".join(text[start:start + ASK_EXCERPT_CHARS].split())})
    return out


def block_visuals(module: dict[str, Any], chapter: int, block: int) -> list[dict[str, Any]]:
    """Every figure and equation printed in ONE lesson, in the order it is read.

    Read straight off the module -- these are the book's own blocks, so the asset
    name is the package's, never the client's."""
    try:
        item = module["tutorialData"]["sections"][chapter - 1]["items"][block - 1]
    except (KeyError, IndexError, TypeError):
        return []
    if not isinstance(item, dict):
        return []
    out: list[dict[str, Any]] = []
    for content in item.get("blocks", []) or []:
        if isinstance(content, dict) and content.get("type") in ("figure", "equation"):
            out.append(content)
    return out


def visual_context(visuals: list[dict[str, Any]]) -> str:
    """LAYER 1. What the package already knows about the page's visuals, as text.

    Costs a few hundred characters and is sent on EVERY ask, because it is the
    difference between "I cannot see the figure" and "Figure 2-9 is a histogram
    of income categories" -- and, for an equation, between guessing and reading
    the actual LaTeX. Capped, and scoped to the open lesson only.
    """
    if not visuals:
        return ""
    lines: list[str] = []
    budget = ASK_VISUAL_CHARS
    for visual in visuals:
        title = str(visual.get("title") or "").strip() or ("Equation" if visual.get("type") == "equation" else "Figure")
        caption = str(visual.get("caption") or "").strip()
        entry = [f"[{title}] {caption}" if caption else f"[{title}]"]
        alt = str(visual.get("alt") or "").strip()
        # alt is usually just "<title>: <caption>" -- only worth sending when it
        # actually carries something the caption does not.
        if alt and alt not in (f"{title}: {caption}", caption, title):
            entry.append(f"  alt text: {alt}")
        # Written by a sibling backfill; absent from every figure today, which is
        # exactly why the vision layer below exists.
        description = str(visual.get("description") or "").strip()
        if description:
            entry.append(f"  what it shows: {description}")
        if visual.get("type") == "equation":
            latex = str(visual.get("latex") or "").strip()
            if latex:
                entry.append(f"  LaTeX (read this, it is the equation itself): {latex}")
            explain = str(visual.get("explain") or "").strip()
            if explain:
                explain = explain[:ASK_VISUAL_EXPLAIN_CHARS].rstrip()
                entry.append(f"  the lesson's own note on it: {explain}")
        elif not description:
            entry.append("  (no written description of this picture is stored)")
        text = "\n".join(entry)
        if len(text) + 1 > budget:
            break
        budget -= len(text) + 1
        lines.append(text)
    if not lines:
        return ""
    return ("VISUALS PRINTED IN THIS LESSON\nThese are the book's own figures and equations, in the order they "
            "appear on the page the reader is looking at. Refer to one by its title, e.g. \"Figure 2-9\". "
            "Unless an image is attached below you have NOT seen the picture itself -- say so plainly rather "
            "than inventing what is in it.\n\n" + "\n".join(lines))


def has_description(visual: dict[str, Any]) -> bool:
    """Does this visual carry a written description good enough to answer from?

    Length is the whole test on purpose. The backfill writes a grounded
    paragraph; anything under ASK_DESCRIPTION_MIN_CHARS is a stub or a repeated
    title, and letting a stub suppress the picture would make the tutor answer
    a figure question out of nothing at all.
    """
    return len(str(visual.get("description") or "").strip()) >= ASK_DESCRIPTION_MIN_CHARS


def ask_wants_image(question: str, visuals: list[dict[str, Any]]) -> tuple[list[dict[str, Any]], str]:
    """LAYER 2 TRIGGER. Which of this lesson's figures, if any, must actually be SEEN.

    Returns (figures to attach, why). The reason is "none" when the question was
    never about a picture on this page, "described" when it WAS but layer 1's
    stored description already answers it, and "vision" when a crop must go out.
    Only the reason tells "described" apart from "none", and the reader is shown
    the difference -- see ask_notice().

    Returns [] for an ordinary question -- and that is the point. Three conditions
    must ALL hold, so a text question cannot reach the expensive path:

      1. THIS LESSON CONTAINS A FIGURE. An equation is excluded on purpose: 88 of
         90 carry LaTeX, which layer 1 already sends, so sending a picture of one
         buys nothing. A lesson with no figure can never escalate, whatever is asked.
      2. THE QUESTION POINTS AT A PICTURE -- either a book reference ("Figure 2-9")
         or a DETERMINER plus a visual noun ("the chart", "this histogram"). The
         determiner is the tight part: "how do I plot a histogram in pandas?" has
         the noun but no determiner pointing at the page, so it does not match.
         A bare visual noun never fires.
      3. LAYER 1 CANNOT ANSWER IT -- the target figure has NO usable stored
         `description`. A figure that carries one is answered from that text and
         the picture is never sent, whatever the question is (user ruling,
         22-09-26: a written description is steady, a vision reading is not).
         Before the backfill every figure was description-less, so this condition
         was always true and every figure escalated; that is the behaviour this
         replaces, not a behaviour it breaks.
    """
    figures = [v for v in visuals if v.get("type") == "figure" and v.get("asset")]
    if not figures:
        return [], "none"                           # 1
    named = ASK_FIGURE_REF.search(question)
    if not (named or ASK_VISUAL_DEICTIC.search(question)):
        return [], "none"                           # 2
    targets: list[dict[str, Any]] = []
    if named:
        wanted = {f"fig-{named.group(1)}-{named.group(2)}", f"fig-{named.group(1)}.{named.group(2)}"}
        label = f"{named.group(1)}-{named.group(2)}"
        for figure in figures:
            title = str(figure.get("title") or "")
            if str(figure.get("asset") or "") in wanted or label in title.replace(".", "-"):
                targets.append(figure)
        # A number that is NOT on this page. Measured 22-09-26: asking "what does
        # Figure 2-9 show?" while ch02-b09 was open attached Figures 2-16 and 2-14
        # and the tutor answered off the wrong pictures. A named figure we do not
        # have is a question the images on this page cannot answer, so send none
        # and let it say so from text.
        if not targets:
            return [], "none"
    # No number given: the reader is pointing at what is in front of them.
    targets = targets or figures
    # 3. Only the figures layer 1 is BLIND to. A figure whose description the
    #    backfill wrote is answered from that description -- dropping it here is
    #    what stops the expensive, variable vision call once the text is good
    #    enough. If every target has one, nothing is sent at all.
    blind = [t for t in targets if not has_description(t)]
    if not blind:
        return [], "described"                      # 3
    return blind[:ASK_VISION_MAX_IMAGES], "vision"


def ask_notice(reason: str, images: list[tuple[str, bytes]]) -> str:
    """One line saying HOW the tutor got its answer, prepended to the reply.

    WHY THIS IS IN THE ANSWER AND NOT A NEW FIELD. The reply already carries
    `vision` and `figures`, and the page ignores both: js/app.js renders exactly
    three things -- the SOURCE badge, its page number, and `answer`. That file is
    frozen, so `answer` is the only server-controlled thing the reader ever sees.
    A new key would be true, logged, and invisible.

    WHAT THIS DOES NOT FIX. It cannot make the WAIT legible. The reply is one
    JSON at the end of the call, so nothing the server writes can reach the
    screen while the reader is waiting -- the grey "Reading the lesson..." line
    is written by the page at submit time and never changes. Reading a figure
    took 4.6-26.6 s measured 22-09-26 against 4.9 s for a text ask, and during
    that gap the page says the same thing either way. Telling the two apart
    while it happens needs a client change; this line is the honest half that
    can be done from here, and it lands the moment the answer does.
    """
    if images:
        titles = ", ".join(title for title, _ in images)
        return (f"_Read the picture — {titles}. Looking at a figure takes several times longer than "
                "a text answer, so this one was slower._")
    if reason == "vision":
        # The trigger fired but no crop went out: the budget could not pay
        # ASK_VISION_COST in full, or the file was missing/oversized. The reader
        # is owed that, because the answer is weaker than it looks.
        return "_Answered from the lesson text only — the picture itself was not attached this time._"
    if reason == "described":
        # Layer 1 had a written description of the figure, so the picture was not
        # needed. Worth saying: it is why this answer came back fast.
        return "_Answered from the book's own written description of the figure, without looking at the picture._"
    return ""


def figure_bytes(module_id: str, asset: str) -> bytes | None:
    """The PNG for one of THIS book's figures, or None.

    PREFERS `<asset>.model.png` (22-09-26). The importer writes every crop
    TWICE: `<asset>.png` is the one the PAGE displays, and `<asset>.model.png`
    is the one it makes for a model -- same picture, about a third of the bytes
    (measured: fig-2-10 25,855 vs 65,856; fig-2-11 84,447 vs 246,084). Sending
    the display crop was uploading two thirds more than the provider needs on
    the slowest call this app makes. Falls back to the display crop when a book
    has no model variant, so an older package still answers.

    Same containment rule as send_book(): the module id and the asset id are
    pattern-checked and the resolved path must stay inside this book's own
    assets/ folder. The id comes from module.json, never from the request --
    there is no client-supplied path anywhere on this route.
    """
    if not MODULE_ID.match(module_id or "") or not ASSET_ID.match(asset or ""):
        return None
    book = (LIBRARY_ROOT / module_id).resolve()
    for name in (f"{asset}.model.png", f"{asset}.png"):
        target = (book / "assets" / name).resolve()
        if not str(target).startswith(str(book) + os.sep) or not target.is_file():
            continue
        if target.stat().st_size > ASK_VISION_MAX_BYTES:
            continue
        return target.read_bytes()
    return None


def ask_tutor(config: "ProviderConfig", chapter_title: str, lesson_term: str, lesson: str,
              question: str, history: list[dict[str, str]], excerpts: list[dict[str, Any]],
              visuals: list[dict[str, Any]] | None = None,
              images: list[tuple[str, bytes]] | None = None) -> dict[str, Any]:
    context = [f"THE LESSON THEY ARE READING\nChapter: {chapter_title}\nLesson: {lesson_term}\n\n{lesson}"]
    # LAYER 1. The page's figures and equations as text. source_for_block() drops
    # those blocks when it builds `lesson`, so without this the tutor cannot even
    # name a figure that is on the reader's screen.
    seen = visual_context(visuals or [])
    if seen:
        context.append(seen)
    if excerpts:
        joined = "\n\n".join(f"[book page {e['page']}]\n{e['text']}" for e in excerpts)
        context.append("BOOK EXCERPTS THAT MAY BE RELEVANT\n\n" + joined)
    if images:
        # LAYER 2. An attached crop is the book's own figure, printed in the lesson
        # in front of them -- so it is the LESSON, and the existing SOURCE: contract
        # needs no new value. The persona above is untouched.
        titles = ", ".join(title for title, _ in images)
        context.append(f"ATTACHED IMAGE(S): {titles}. This is the book's own figure from the lesson they are "
                       "reading, so it counts as THE LESSON (answer with SOURCE: lesson). Read what is "
                       "actually in the picture -- the axes and their units, what the shapes or bars do, "
                       "where the mass sits, which parts stand out -- and answer from that, not from what "
                       "a figure with this caption usually looks like.")
    messages: list[dict[str, Any]] = [{"role": "system", "content": ASK_SYSTEM},
                                      {"role": "system", "content": "\n\n".join(context)}]
    messages.extend(history[-ASK_HISTORY_TURNS:])
    if images:
        parts: list[dict[str, Any]] = [{"type": "text", "text": question}]
        for _, raw in images:
            encoded = base64.b64encode(raw).decode("ascii")
            parts.append({"type": "image_url", "image_url": {"url": f"data:image/png;base64,{encoded}"}})
        messages.append({"role": "user", "content": parts})
    else:
        # A text ask stays byte-identical to what it has always sent.
        messages.append({"role": "user", "content": question})
    body = {"model": config.model, "messages": messages, "temperature": 0.4, "stream": True}
    request = Request(config.api_url, data=json.dumps(body).encode("utf-8"),
                      headers={"Authorization": f"Bearer {config.api_key}", "Content-Type": "application/json"},
                      method="POST")
    try:
        with urlopen(request, timeout=PROVIDER_TIMEOUT_SECONDS) as response:
            content = response_content(response.read(), response.headers.get("Content-Type", ""))
    except HTTPError as error:
        raise ValueError(f"Provider request failed ({error.code}).") from error
    except (URLError, TimeoutError, OSError) as error:
        raise ValueError("Provider could not be reached.") from error
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as error:
        raise ValueError("Provider returned an invalid response.") from error
    content = (content or "").strip()
    if not content:
        raise ValueError("The model returned an empty answer.")
    source, page = "general", None
    match = SOURCE_LINE.match(content)
    if match:
        source = match.group(1).lower()
        found = re.search(r"p\.?\s*(\d{1,4})", match.group(0))
        page = int(found.group(1)) if found else None
        content = content[match.end():].lstrip("\n").strip()
    return {"answer": content, "source": source, "page": page,
            "pages": [e["page"] for e in excerpts],
            # Extra keys only -- the page ignores what it does not know. They exist
            # so a vision ask is never silent: it shows up here and in the ask log.
            "vision": bool(images),
            "figures": [title for title, _ in (images or [])]}


def grade_exercises(config: "ProviderConfig", chapter_title: str,
                    answers: list[dict[str, Any]], excerpts: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """One model call for the whole submit, not one per exercise.

    A chapter has 4-19 exercises. Nineteen calls per submit would burn a free
    tier's weekly allowance in a handful of chapters, and the model marks better
    seeing the whole set anyway -- it can tell an answer that belongs to the next
    exercise from one that is simply wrong.
    """
    lines = []
    for item in answers:
        lines.append(f"EXERCISE {item['n']}\nQuestion: {item['question']}\nTheir answer: {item['answer'] or '(left blank)'}")
    context = [f"CHAPTER\n{chapter_title}"]
    if excerpts:
        context.append("BOOK EXCERPTS FROM THIS CHAPTER\n\n" + "\n\n".join(
            f"[book page {e['page']}]\n{e['text']}" for e in excerpts))
    body = {
        "model": config.model,
        "messages": [
            {"role": "system", "content": EXERCISE_SYSTEM},
            {"role": "system", "content": "\n\n".join(context)},
            {"role": "user", "content": "\n\n".join(lines)},
        ],
        "temperature": 0.2,
        "stream": True,
    }
    request = Request(config.api_url, data=json.dumps(body).encode("utf-8"),
                      headers={"Authorization": f"Bearer {config.api_key}", "Content-Type": "application/json"},
                      method="POST")
    try:
        with urlopen(request, timeout=PROVIDER_TIMEOUT_SECONDS) as response:
            content = response_content(response.read(), response.headers.get("Content-Type", ""))
    except HTTPError as error:
        raise ValueError(f"Provider request failed ({error.code}).") from error
    except (URLError, TimeoutError, OSError) as error:
        raise ValueError("Provider could not be reached.") from error
    except (KeyError, IndexError, TypeError, json.JSONDecodeError) as error:
        raise ValueError("Provider returned an invalid response.") from error

    text = strip_code_fence((content or "").strip())
    if not text:
        raise ValueError("The model returned an empty reply.")
    # Some models wrap the object in a sentence even when told not to. Take the
    # outermost braces rather than failing the whole submit on a stray prefix.
    try:
        parsed = json.loads(text)
    except json.JSONDecodeError:
        start, end = text.find("{"), text.rfind("}")
        if start < 0 or end <= start:
            raise ValueError("The model did not return JSON.")
        try:
            parsed = json.loads(text[start:end + 1])
        except json.JSONDecodeError as error:
            raise ValueError("The model returned malformed JSON.") from error

    rows = parsed.get("results") if isinstance(parsed, dict) else parsed
    if not isinstance(rows, list):
        raise ValueError("The model returned no results.")
    marked: dict[int, dict[str, Any]] = {}
    for row in rows:
        if not isinstance(row, dict):
            continue
        try:
            n = int(row.get("n"))
        except (TypeError, ValueError):
            continue
        verdict = str(row.get("verdict", "")).strip().lower()
        if verdict not in EXERCISE_VERDICTS:
            verdict = "partial"
        marked[n] = {"n": n, "verdict": verdict, "feedback": str(row.get("feedback", "")).strip()[:1_200]}
    # An exercise the model skipped is NOT silently passed. It comes back as
    # unmarked so the page can say so and the reader can submit again.
    return [marked.get(item["n"], {"n": item["n"], "verdict": "unmarked",
                                   "feedback": "The model did not mark this one. Submit again."})
            for item in answers]
